-- ============================================================
-- RENTIFY Full Schema Migration
-- Adds: locations, categories, item_specifications,
--       rental_transactions + updates items table
-- ============================================================

-- ── LOCATIONS ────────────────────────────────────────────────
create table if not exists public.locations (
  id          text primary key,              -- e.g. L001
  name        text not null,
  building    text not null default '',
  street      text not null default '',
  city        text not null default 'Edmonton',
  province    text not null default 'AB',
  postal_code text not null default '',
  contact_email text not null default '',
  contact_phone text not null default '',
  status      text not null default 'active' check (status in ('active','inactive')),
  hours       text not null default 'Mon-Fri 9AM-5PM',
  created_at  timestamptz not null default now()
);

alter table public.locations enable row level security;

drop policy if exists "locations_select_all" on public.locations;
create policy "locations_select_all"
  on public.locations for select to public using (true);

drop policy if exists "locations_admin_write" on public.locations;
create policy "locations_admin_write"
  on public.locations for all to authenticated using (true) with check (true);

-- Seed two starter locations
insert into public.locations (id, name, building, street, city, province, postal_code, hours)
values
  ('L001', 'Main Campus - Engineering Building', 'Engineering Bldg', '123 University Dr', 'Edmonton', 'AB', 'T6G 2H1', 'Mon-Fri 9AM-5PM'),
  ('L002', 'South Campus - Science Building',    'Science Bldg',     '456 College Ave',   'Edmonton', 'AB', 'T6G 3K2', 'Mon-Fri 8AM-6PM')
on conflict (id) do nothing;


-- ── CATEGORIES ───────────────────────────────────────────────
create table if not exists public.categories (
  id           text primary key,             -- e.g. C-TXTBK
  name         text not null,
  display_name text not null,
  description  text not null default ''
);

alter table public.categories enable row level security;

drop policy if exists "categories_select_all" on public.categories;
create policy "categories_select_all"
  on public.categories for select to public using (true);

insert into public.categories (id, name, display_name, description)
values
  ('C-TXTBK', 'Textbooks',     'Textbooks & Books',  'Academic textbooks and course materials'),
  ('C-ELEC',  'Electronics',   'Electronics',        'Laptops, calculators, and electronic devices'),
  ('C-LAB',   'Lab Equipment', 'Lab Equipment',      'Lab tools and scientific instruments')
on conflict (id) do nothing;


-- ── UPDATE ITEMS TABLE ────────────────────────────────────────
-- Add rental-specific columns to the existing items table
alter table public.items
  add column if not exists location_id    text references public.locations(id),
  add column if not exists category_id   text references public.categories(id),
  add column if not exists daily_rate    numeric(10,2) not null default 0 check (daily_rate >= 0),
  add column if not exists weekly_rate   numeric(10,2) not null default 0 check (weekly_rate >= 0),
  add column if not exists semester_rate numeric(10,2) not null default 0 check (semester_rate >= 0),
  add column if not exists deposit_amount numeric(10,2) not null default 0 check (deposit_amount >= 0),
  add column if not exists condition     text not null default 'good'
                                           check (condition in ('new','like_new','good','fair')),
  add column if not exists item_status   text not null default 'available'
                                           check (item_status in ('available','rented','maintenance')),
  add column if not exists available_quantity int not null default 1,
  add column if not exists total_quantity     int not null default 1,
  add column if not exists video_url     text not null default '',
  add column if not exists owner_rating  numeric(2,1) not null default 0;


-- ── ITEM SPECIFICATIONS ───────────────────────────────────────
create table if not exists public.item_specifications (
  id             bigint generated by default as identity primary key,
  item_id        bigint not null references public.items(id) on delete cascade,
  attribute_name text not null,
  attribute_value text not null,
  created_at     timestamptz not null default now()
);

create index if not exists item_specs_item_id_idx on public.item_specifications(item_id);

alter table public.item_specifications enable row level security;

drop policy if exists "specs_select_all" on public.item_specifications;
create policy "specs_select_all"
  on public.item_specifications for select to public using (true);

drop policy if exists "specs_owner_write" on public.item_specifications;
create policy "specs_owner_write"
  on public.item_specifications for all to authenticated using (true) with check (true);


-- ── RENTAL TRANSACTIONS ───────────────────────────────────────
create table if not exists public.rental_transactions (
  id                  text primary key,           -- e.g. R9001
  renter_id           uuid not null references auth.users(id) on delete cascade,
  item_id             bigint not null references public.items(id),
  pickup_location_id  text not null references public.locations(id),
  return_location_id  text references public.locations(id),
  start_date          date not null,
  expected_return_date date not null,
  actual_return_date  date,
  rental_type         text not null check (rental_type in ('daily','weekly','semester')),
  num_days            int not null default 1,
  base_price          numeric(10,2) not null default 0,
  deposit_amount      numeric(10,2) not null default 0,
  deposit_refunded    boolean not null default false,
  location_change_fee numeric(10,2) not null default 0,
  late_fee            numeric(10,2) not null default 0,
  damage_fee          numeric(10,2) not null default 0,
  total_cost          numeric(10,2) not null default 0,
  payment_method      text not null default 'credit_card',
  status              text not null default 'active'
                        check (status in ('active','returned','overdue','cancelled')),
  created_at          timestamptz not null default now()
);

create index if not exists rentals_renter_id_idx  on public.rental_transactions(renter_id);
create index if not exists rentals_item_id_idx    on public.rental_transactions(item_id);
create index if not exists rentals_status_idx     on public.rental_transactions(status);

alter table public.rental_transactions enable row level security;

drop policy if exists "rentals_select_own" on public.rental_transactions;
create policy "rentals_select_own"
  on public.rental_transactions for select to authenticated
  using (auth.uid() = renter_id);

drop policy if exists "rentals_insert_own" on public.rental_transactions;
create policy "rentals_insert_own"
  on public.rental_transactions for insert to authenticated
  with check (auth.uid() = renter_id);

drop policy if exists "rentals_update_own" on public.rental_transactions;
create policy "rentals_update_own"
  on public.rental_transactions for update to authenticated
  using (auth.uid() = renter_id);


-- ── ADD RENTAL FIELDS TO PROFILES ────────────────────────────
alter table public.profiles
  add column if not exists phone_number   text not null default '',
  add column if not exists student_id     text not null default '',
  add column if not exists is_banned      boolean not null default false,
  add column if not exists banned_until   timestamptz,
  add column if not exists rating         numeric(2,1) not null default 0,
  add column if not exists role           text not null default 'student'
                                            check (role in ('student','admin'));
