create table if not exists public.todos (
  id bigint generated by default as identity primary key,
  task text not null,
  inserted_at timestamptz not null default now()
);

alter table public.todos enable row level security;

create policy "todos_select_all"
on public.todos
for select
to anon
using (true);

create policy "todos_insert_all"
on public.todos
for insert
to anon
with check (true);